"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Save, Send } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import CountrySelect from "@/components/ui/CountrySelect";
import type { Opportunity } from "@/types";

type FormState={title:string;kind:string;work_mode:string;country:string;city:string;experience_level:string;description:string;responsibilities:string;requirements:string;required_skills:string;preferred_skills:string;salary_min:string;salary_max:string;salary_currency:string;compensation_period:string;salary_visible:boolean;slots:string;external_apply_url:string;application_deadline:string};
const blank:FormState={title:"",kind:"job",work_mode:"remote",country:"",city:"",experience_level:"entry",description:"",responsibilities:"",requirements:"",required_skills:"",preferred_skills:"",salary_min:"",salary_max:"",salary_currency:"XOF",compensation_period:"month",salary_visible:true,slots:"1",external_apply_url:"",application_deadline:""};
function lines(v:string){return v.split(/\n|,/).map(x=>x.trim()).filter(Boolean)}
function dtLocal(value?:string|null){if(!value)return "";const d=new Date(value);const off=d.getTimezoneOffset()*60000;return new Date(d.getTime()-off).toISOString().slice(0,16)}
export default function EmployerOpportunityForm({existing}:{existing?:Opportunity|null}){const router=useRouter();const [f,setF]=useState<FormState>(existing?{title:existing.title,kind:existing.kind,work_mode:existing.work_mode,country:existing.country,city:existing.city,experience_level:existing.experience_level,description:existing.description||"",responsibilities:(existing.responsibilities||[]).join("\n"),requirements:(existing.requirements||[]).join("\n"),required_skills:existing.required_skills.join(", "),preferred_skills:existing.preferred_skills.join(", "),salary_min:existing.salary_min||"",salary_max:existing.salary_max||"",salary_currency:existing.salary_currency||"XOF",compensation_period:existing.compensation_period||"month",salary_visible:existing.salary_visible,slots:String(existing.slots||1),external_apply_url:existing.external_apply_url||"",application_deadline:dtLocal(existing.application_deadline)}:blank);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [saved,setSaved]=useState<Opportunity|null>(existing||null);
  function set<K extends keyof FormState>(k:K,v:FormState[K]){setF(x=>({...x,[k]:v}))}
  async function save(submit=false){setBusy(true);setError("");try{const payload={...f,responsibilities:lines(f.responsibilities),requirements:lines(f.requirements),required_skills:lines(f.required_skills),preferred_skills:lines(f.preferred_skills),salary_min:f.salary_min||null,salary_max:f.salary_max||null,slots:Number(f.slots||1),application_deadline:f.application_deadline?new Date(f.application_deadline).toISOString():null};let row:Opportunity;if(saved)row=await api.patch<Opportunity>(`/opportunities/employer/opportunities/${saved.id}/`,payload);else row=await api.post<Opportunity>("/opportunities/employer/opportunities/",payload);setSaved(row);if(submit){row=await api.post<Opportunity>(`/opportunities/employer/opportunities/${row.id}/submit/`,{});setSaved(row);}router.push(`/dashboard/employer/opportunities/${row.id}`);router.refresh();}catch(e){setError(e instanceof ApiError?e.message:"Impossible d'enregistrer l'opportunité.")}finally{setBusy(false)}}
  return <div className="space-y-5"><section className="card p-5 sm:p-6"><h2 className="font-bold">Informations principales</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Intitulé *"><input required value={f.title} onChange={e=>set("title",e.target.value)} className="input-admin w-full" placeholder="Ex. Analyste Power BI junior"/></Field><Field label="Type"><select value={f.kind} onChange={e=>set("kind",e.target.value)} className="input-admin w-full"><option value="job">Emploi</option><option value="internship">Stage</option><option value="freelance">Mission freelance</option><option value="apprenticeship">Alternance</option><option value="volunteer">Volontariat</option></select></Field><Field label="Mode"><select value={f.work_mode} onChange={e=>set("work_mode",e.target.value)} className="input-admin w-full"><option value="remote">À distance</option><option value="hybrid">Hybride</option><option value="onsite">Sur site</option></select></Field><Field label="Niveau d'expérience"><select value={f.experience_level} onChange={e=>set("experience_level",e.target.value)} className="input-admin w-full"><option value="entry">Débutant / premier poste</option><option value="junior">Junior</option><option value="mid">Intermédiaire</option><option value="senior">Senior</option><option value="lead">Lead / management</option></select></Field><Field label="Pays"><CountrySelect value={f.country} onChange={v=>set("country",v)} emptyLabel={f.work_mode==="remote"?"International / choisir un pays":"Sélectionnez un pays"}/></Field><Field label="Ville"><input value={f.city} onChange={e=>set("city",e.target.value)} className="input-admin w-full" placeholder="Dakar"/></Field></div><Field label="Description *"><textarea rows={8} value={f.description} onChange={e=>set("description",e.target.value)} className="input-admin w-full" placeholder="Présentez le rôle, la mission, l'équipe et le contexte."/></Field></section>
    <section className="card p-5 sm:p-6"><h2 className="font-bold">Mission & prérequis</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><Field label="Responsabilités (une par ligne)"><textarea rows={7} value={f.responsibilities} onChange={e=>set("responsibilities",e.target.value)} className="input-admin w-full"/></Field><Field label="Prérequis (un par ligne)"><textarea rows={7} value={f.requirements} onChange={e=>set("requirements",e.target.value)} className="input-admin w-full"/></Field><Field label="Compétences requises"><textarea rows={4} value={f.required_skills} onChange={e=>set("required_skills",e.target.value)} className="input-admin w-full" placeholder="Excel, Power BI, SQL"/><span className="mt-1 block text-[11px] text-gray-400">Séparez par virgule ou ligne. Ces compétences servent au matching.</span></Field><Field label="Compétences appréciées"><textarea rows={4} value={f.preferred_skills} onChange={e=>set("preferred_skills",e.target.value)} className="input-admin w-full" placeholder="Python, anglais"/></Field></div></section>
    <section className="card p-5 sm:p-6"><h2 className="font-bold">Rémunération & candidature</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Minimum"><input type="number" min="0" step="0.01" value={f.salary_min} onChange={e=>set("salary_min",e.target.value)} className="input-admin w-full"/></Field><Field label="Maximum"><input type="number" min="0" step="0.01" value={f.salary_max} onChange={e=>set("salary_max",e.target.value)} className="input-admin w-full"/></Field><Field label="Devise"><select value={f.salary_currency} onChange={e=>set("salary_currency",e.target.value)} className="input-admin w-full"><option>XOF</option><option>XAF</option><option>EUR</option><option>USD</option><option>MAD</option><option>CDF</option></select></Field><Field label="Période"><select value={f.compensation_period} onChange={e=>set("compensation_period",e.target.value)} className="input-admin w-full"><option value="month">Par mois</option><option value="year">Par an</option><option value="hour">Par heure</option><option value="project">Par projet</option></select></Field><Field label="Nombre de postes"><input type="number" min="1" max="999" value={f.slots} onChange={e=>set("slots",e.target.value)} className="input-admin w-full"/></Field><Field label="Date limite"><input type="datetime-local" value={f.application_deadline} onChange={e=>set("application_deadline",e.target.value)} className="input-admin w-full"/></Field><Field label="Lien externe de candidature"><input type="url" value={f.external_apply_url} onChange={e=>set("external_apply_url",e.target.value)} className="input-admin w-full" placeholder="https://..."/></Field><label className="mt-5 flex items-center gap-2 text-sm"><input type="checkbox" checked={f.salary_visible} onChange={e=>set("salary_visible",e.target.checked)} className="h-4 w-4"/>Afficher la rémunération</label></div></section>
    {error&&<div className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="flex flex-wrap justify-end gap-2"><button disabled={busy} onClick={()=>void save(false)} className="btn-outline">{busy?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>}Enregistrer le brouillon</button><button disabled={busy} onClick={()=>void save(true)} className="btn-primary">{busy?<Loader2 size={15} className="animate-spin"/>:<Send size={15}/>}Soumettre à LearnEas</button></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-700">{label}</span>{children}</label>}
