# Generated manually for LearnEas v46.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0005_lesson_adaptive_streaming"),
        ("enrollments", "0004_lessonnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(blank=True, max_length=240)),
                ("brief", models.TextField()),
                ("instructions", models.TextField(blank=True)),
                ("objectives", models.JSONField(blank=True, default=list)),
                ("deliverables", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("due_days_after_enrollment", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_score", models.PositiveSmallIntegerField(default=100)),
                ("passing_score", models.PositiveSmallIntegerField(default=60)),
                ("required_for_certificate", models.BooleanField(default=False)),
                ("allow_resubmission", models.BooleanField(default=True)),
                ("max_resubmissions", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_assignments", to="catalog.course")),
            ],
            options={"ordering": ["course_id", "order", "id"]},
        ),
        migrations.CreateModel(
            name="ProjectSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=220)),
                ("summary", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("artifact_file", models.FileField(blank=True, null=True, upload_to="projects/submissions/%Y/%m/")),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="projects/covers/%Y/%m/")),
                ("skills", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("draft", "Brouillon"), ("submitted", "À corriger"), ("changes_requested", "Modifications demandées"), ("approved", "Validé"), ("rejected", "Refusé")], db_index=True, default="draft", max_length=24)),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("instructor_feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resubmission_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="submissions", to="projects.projectassignment")),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_submissions", to="enrollments.courseenrollment")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_project_submissions", to=settings.AUTH_USER_MODEL)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_submissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="ProjectSubmissionRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revision_number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=220)),
                ("summary", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("artifact_file", models.FileField(blank=True, null=True, upload_to="projects/revisions/%Y/%m/")),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="projects/revision-covers/%Y/%m/")),
                ("skills", models.JSONField(blank=True, default=list)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="projects.projectsubmission")),
            ],
            options={"ordering": ["-revision_number"]},
        ),
        migrations.CreateModel(
            name="PortfolioProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_public", models.BooleanField(db_index=True, default=False)),
                ("title", models.CharField(blank=True, max_length=180)),
                ("about", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("website_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("open_to_work", models.BooleanField(default=False)),
                ("show_country", models.BooleanField(default=True)),
                ("show_project_scores", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["slug"]},
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="portfolio/items/%Y/%m/")),
                ("external_url", models.URLField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False, editable=False)),
                ("verified_course_title", models.CharField(blank=True, editable=False, max_length=220)),
                ("verified_assignment_title", models.CharField(blank=True, editable=False, max_length=220)),
                ("verified_instructor_name", models.CharField(blank=True, editable=False, max_length=220)),
                ("verified_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("verified_score", models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ("verified_max_score", models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_items", to=settings.AUTH_USER_MODEL)),
                ("source_submission", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="portfolio_item", to="projects.projectsubmission")),
            ],
            options={"ordering": ["-featured", "order", "-updated_at"]},
        ),
        migrations.AddConstraint(
            model_name="projectassignment",
            constraint=models.UniqueConstraint(fields=("course", "slug"), name="uniq_project_assignment_course_slug"),
        ),
        migrations.AddConstraint(
            model_name="projectsubmission",
            constraint=models.UniqueConstraint(fields=("assignment", "student"), name="uniq_project_submission_assignment_student"),
        ),
        migrations.AddConstraint(
            model_name="projectsubmissionrevision",
            constraint=models.UniqueConstraint(fields=("submission", "revision_number"), name="uniq_project_submission_revision"),
        ),
        migrations.AddIndex(model_name="projectassignment", index=models.Index(fields=["course", "published", "order"], name="proj_assign_course_pub_idx")),
        migrations.AddIndex(model_name="projectsubmission", index=models.Index(fields=["assignment", "status", "-updated_at"], name="proj_sub_assign_status_idx")),
        migrations.AddIndex(model_name="projectsubmission", index=models.Index(fields=["student", "status", "-updated_at"], name="proj_sub_student_status_idx")),
        migrations.AddIndex(model_name="portfolioitem", index=models.Index(fields=["owner", "is_public", "featured"], name="portfolio_owner_public_idx")),
    ]
