"use client";

import { FormEvent, Suspense, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronRight, LifeBuoy, Loader2, MessageSquareText, Plus, Send, ShieldAlert, X } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { api, ApiError } from "@/lib/api";
import { useAuthGuard } from "@/hooks/useAuthGuard";
import GuardScreen from "@/components/ui/GuardScreen";

type Paginated<T> = { results: T[]; count: number; next: string | null; previous: string | null };
type Ticket = {
  id:number; reference:string; subject:string; category:string; priority:string; status:string; assigned_to_name:string;
  last_message_at:string|null; last_message_preview:string; message_count:number; created_at:string; updated_at:string;
};
type TicketMessage = { id:number; author_name:string; author_role:string; body:string; is_staff_reply:boolean; created_at:string };
type Report = { id:number; target_type:string; target_id:string; target_label:string; reason:string; details:string; status:string; severity:string; action_taken:string; resolution_note:string; created_at:string; updated_at:string };

const ticketStatus:Record<string,string>={open:"Ouvert",in_progress:"En cours",waiting_user:"Votre réponse attendue",resolved:"Résolu",closed:"Fermé"};
const reportStatus:Record<string,string>={pending:"À examiner",reviewing:"En cours d’examen",actioned:"Action effectuée",dismissed:"Classé sans suite"};
const categories=[["account","Compte et connexion"],["payment","Paiement et remboursement"],["learning","Cours et apprentissage"],["technical","Problème technique"],["recruitment","Emploi et recrutement"],["safety","Sécurité et modération"],["other","Autre"]] as const;
const reasons=[["harassment","Harcèlement ou menace"],["spam","Spam"],["fraud","Fraude ou arnaque"],["impersonation","Usurpation d’identité"],["inappropriate","Contenu inapproprié"],["illegal","Contenu potentiellement illégal"],["copyright","Droits d’auteur"],["misinformation","Information trompeuse"],["other","Autre"]] as const;
const targets=[["user","Utilisateur"],["review","Avis"],["comment","Commentaire"],["course","Cours"],["pdf","PDF"],["formation","Formation"],["opportunity","Opportunité"],["message","Message"],["other","Autre"]] as const;

function unwrap<T>(data:Paginated<T>|T[]):T[]{return Array.isArray(data)?data:data.results||[]}
function errorText(e:unknown){return e instanceof ApiError?e.message:"Une erreur est survenue."}

function SupportPageContent(){
  const {ready}=useAuthGuard();
  const searchParams=useSearchParams();
  const initialView=searchParams.get("view")==="reports"?"reports":"tickets";
  const [view,setView]=useState<"tickets"|"reports">(initialView);
  const [tickets,setTickets]=useState<Ticket[]>([]); const [reports,setReports]=useState<Report[]>([]);
  const [selected,setSelected]=useState<Ticket|null>(null); const [messages,setMessages]=useState<TicketMessage[]>([]);
  const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const [ticketForm,setTicketForm]=useState({subject:"",category:"technical",priority:"normal",initial_message:""});
  const [reply,setReply]=useState("");
  const [reportForm,setReportForm]=useState({
    target_type:searchParams.get("target_type")||"other", target_id:searchParams.get("target_id")||"",
    target_label:searchParams.get("target_label")||"", target_url:searchParams.get("target_url")||"",
    reason:"other", details:""
  });

  const load=useCallback(async()=>{if(!ready)return;setLoading(true);setError("");try{const [t,r]=await Promise.all([api.get<Paginated<Ticket>|Ticket[]>("/support/tickets/?ordering=-last_message_at"),api.get<Paginated<Report>|Report[]>("/support/reports/?ordering=-created_at")]);setTickets(unwrap(t));setReports(unwrap(r));}catch(e){setError(errorText(e))}finally{setLoading(false)}},[ready]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{const id=Number(searchParams.get("ticket")||0);if(id&&tickets.length){const row=tickets.find(t=>t.id===id);if(row)void openTicket(row)}},[tickets]); // eslint-disable-line react-hooks/exhaustive-deps

  async function openTicket(ticket:Ticket){setSelected(ticket);setError("");try{setMessages(await api.get<TicketMessage[]>(`/support/tickets/${ticket.id}/messages/`));}catch(e){setError(errorText(e))}}
  async function createTicket(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{const created=await api.post<Ticket>("/support/tickets/",ticketForm);setTicketForm({subject:"",category:"technical",priority:"normal",initial_message:""});setNotice(`Ticket ${created.reference} créé.`);await load();await openTicket(created);}catch(e2){setError(errorText(e2))}finally{setBusy(false)}}
  async function sendReply(e:FormEvent){e.preventDefault();if(!selected||!reply.trim())return;setBusy(true);setError("");try{await api.post(`/support/tickets/${selected.id}/messages/`,{body:reply.trim()});setReply("");const [freshTicket,freshMessages]=await Promise.all([api.get<Ticket>(`/support/tickets/${selected.id}/`),api.get<TicketMessage[]>(`/support/tickets/${selected.id}/messages/`)]);setSelected(freshTicket);setMessages(freshMessages);await load();}catch(e2){setError(errorText(e2))}finally{setBusy(false)}}
  async function closeTicket(){if(!selected)return;setBusy(true);try{const updated=await api.post<Ticket>(`/support/tickets/${selected.id}/close/`,{});setSelected(updated);await load();setNotice(`Ticket ${updated.reference} fermé.`);}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  async function createReport(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{await api.post("/support/reports/",reportForm);setReportForm({target_type:"other",target_id:"",target_label:"",target_url:"",reason:"other",details:""});setNotice("Votre signalement a été transmis à la modération.");await load();}catch(e2){setError(errorText(e2))}finally{setBusy(false)}}

  const activeTickets=useMemo(()=>tickets.filter(t=>!["resolved","closed"].includes(t.status)).length,[tickets]);
  if(!ready)return <GuardScreen/>;
  return <div className="container-app max-w-6xl py-8 sm:py-10">
    <header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-700"><LifeBuoy size={14}/> Centre d’aide KalanPro</div><h1 className="text-2xl font-extrabold sm:text-3xl">Support & sécurité</h1><p className="mt-2 max-w-2xl text-sm text-gray-500">Suivez vos demandes d’assistance et transmettez un signalement confidentiel à l’équipe de modération.</p></div><div className="rounded-xl border border-gray-100 bg-white px-4 py-3 text-sm shadow-sm"><strong>{activeTickets}</strong> ticket{activeTickets!==1?"s":""} actif{activeTickets!==1?"s":""}</div></header>
    <div className="mb-5 flex gap-2 overflow-x-auto border-b border-gray-100 pb-3"><button onClick={()=>setView("tickets")} className={`shrink-0 rounded-lg px-4 py-2 text-sm font-bold ${view==="tickets"?"bg-brand-50 text-brand-700":"text-gray-500 hover:bg-gray-50"}`}><MessageSquareText size={15} className="mr-1.5 inline"/>Mes tickets</button><button onClick={()=>setView("reports")} className={`shrink-0 rounded-lg px-4 py-2 text-sm font-bold ${view==="reports"?"bg-brand-50 text-brand-700":"text-gray-500 hover:bg-gray-50"}`}><ShieldAlert size={15} className="mr-1.5 inline"/>Mes signalements</button></div>
    {error&&<div className="mb-4 rounded-xl border border-red-100 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={15} className="mr-1 inline"/>{error}</div>}{notice&&<div className="mb-4 rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 size={15} className="mr-1 inline"/>{notice}</div>}
    {loading?<div className="card p-10 text-center text-gray-500"><Loader2 className="mx-auto mb-2 animate-spin"/>Chargement…</div>:view==="tickets"?<div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_380px]">
      <section className="space-y-3">{tickets.map(t=><button type="button" key={t.id} onClick={()=>void openTicket(t)} className={`card block w-full p-4 text-left transition hover:border-brand-100 ${selected?.id===t.id?"ring-2 ring-brand-100":""}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-[11px] font-bold text-brand-700">{t.reference}</span><span className="badge bg-gray-50 text-gray-600">{ticketStatus[t.status]||t.status}</span></div><p className="mt-1 truncate font-bold">{t.subject}</p><p className="mt-1 line-clamp-2 text-xs text-gray-500">{t.last_message_preview||"Aucun message"}</p></div><ChevronRight size={17} className="mt-1 shrink-0 text-gray-300"/></div><p className="mt-3 text-[11px] text-gray-400">{t.message_count} message{t.message_count!==1?"s":""} · mise à jour {new Date(t.updated_at).toLocaleString("fr-FR")}</p></button>)}{!tickets.length&&<div className="card p-8 text-center text-sm text-gray-500">Aucun ticket pour le moment.</div>}
      {selected&&<div className="card p-4 sm:p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-brand-700">{selected.reference}</p><h2 className="font-extrabold">{selected.subject}</h2><p className="mt-1 text-xs text-gray-500">{ticketStatus[selected.status]||selected.status}{selected.assigned_to_name?` · ${selected.assigned_to_name}`:""}</p></div><button onClick={()=>setSelected(null)} className="rounded-lg p-2 text-gray-400 hover:bg-gray-50"><X size={16}/></button></div><div className="max-h-[420px] space-y-3 overflow-y-auto rounded-xl bg-gray-50 p-3">{messages.map(m=><div key={m.id} className={`max-w-[88%] rounded-xl p-3 text-sm ${m.is_staff_reply?"bg-navy-950 text-white":"ml-auto bg-white shadow-sm"}`}><p className={`mb-1 text-[10px] font-bold ${m.is_staff_reply?"text-brand-300":"text-gray-400"}`}>{m.is_staff_reply?"Support KalanPro":m.author_name}</p><p className="whitespace-pre-wrap leading-6">{m.body}</p><p className={`mt-2 text-[10px] ${m.is_staff_reply?"text-white/50":"text-gray-400"}`}>{new Date(m.created_at).toLocaleString("fr-FR")}</p></div>)}</div>{selected.status!=="closed"&&<form onSubmit={sendReply} className="mt-4 flex gap-2"><textarea rows={2} value={reply} onChange={e=>setReply(e.target.value)} maxLength={6000} placeholder="Répondre au support…" className="input-admin min-w-0 flex-1"/><button disabled={busy||!reply.trim()} className="btn-primary self-end !px-3"><Send size={15}/></button></form>}<div className="mt-3 flex justify-end">{selected.status!=="closed"&&<button disabled={busy} onClick={()=>void closeTicket()} className="text-xs font-semibold text-gray-500 hover:text-red-600">Fermer ce ticket</button>}</div></div>}
      </section>
      <form onSubmit={createTicket} className="card h-fit p-5 lg:sticky lg:top-24"><h2 className="flex items-center gap-2 font-extrabold"><Plus size={17}/> Nouveau ticket</h2><p className="mt-1 text-xs text-gray-500">Une demande = un sujet, pour garder un suivi clair.</p><div className="mt-4 space-y-3"><label className="label-admin">Sujet<input required minLength={5} maxLength={180} value={ticketForm.subject} onChange={e=>setTicketForm({...ticketForm,subject:e.target.value})} className="input-admin w-full" placeholder="Ex. Paiement débité mais cours inaccessible"/></label><label className="label-admin">Catégorie<select value={ticketForm.category} onChange={e=>setTicketForm({...ticketForm,category:e.target.value})} className="input-admin w-full">{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="label-admin">Priorité<select value={ticketForm.priority} onChange={e=>setTicketForm({...ticketForm,priority:e.target.value})} className="input-admin w-full"><option value="low">Faible</option><option value="normal">Normale</option><option value="high">Haute</option></select></label><label className="label-admin">Description<textarea required rows={6} maxLength={6000} value={ticketForm.initial_message} onChange={e=>setTicketForm({...ticketForm,initial_message:e.target.value})} className="input-admin w-full" placeholder="Décrivez les étapes, le résultat attendu et ce qui s’est passé."/></label><button disabled={busy} className="btn-primary w-full">{busy?<Loader2 size={15} className="animate-spin"/>:<Send size={15}/>}Envoyer au support</button></div></form>
    </div>:<div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_380px]"><section className="space-y-3">{reports.map(r=><article key={r.id} className="card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="badge bg-gray-50 text-gray-600">{reportStatus[r.status]||r.status}</span><span className="badge bg-amber-50 text-amber-700">{r.reason}</span></div><h3 className="mt-2 font-bold">{r.target_label||`${r.target_type} ${r.target_id}`}</h3><p className="mt-1 text-sm text-gray-600">{r.details||"Aucun détail complémentaire."}</p></div><span className="text-xs text-gray-400">#{r.id}</span></div>{r.resolution_note&&<div className="mt-3 rounded-lg bg-emerald-50 p-3 text-xs text-emerald-800"><strong>Décision :</strong> {r.resolution_note}</div>}<p className="mt-3 text-[11px] text-gray-400">Signalé le {new Date(r.created_at).toLocaleString("fr-FR")}</p></article>)}{!reports.length&&<div className="card p-8 text-center text-sm text-gray-500">Aucun signalement transmis.</div>}</section><form onSubmit={createReport} className="card h-fit p-5 lg:sticky lg:top-24"><h2 className="flex items-center gap-2 font-extrabold"><ShieldAlert size={17}/> Signaler un problème</h2><p className="mt-1 text-xs text-gray-500">Ce formulaire est réservé aux problèmes de sécurité, abus, fraude ou contenu inapproprié.</p><div className="mt-4 space-y-3"><label className="label-admin">Élément concerné<select value={reportForm.target_type} onChange={e=>setReportForm({...reportForm,target_type:e.target.value})} className="input-admin w-full">{targets.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="label-admin">Nom / référence<input value={reportForm.target_label} onChange={e=>setReportForm({...reportForm,target_label:e.target.value})} className="input-admin w-full" placeholder="Ex. Cours Excel avancé, utilisateur…"/></label><label className="label-admin">Identifiant (optionnel)<input value={reportForm.target_id} onChange={e=>setReportForm({...reportForm,target_id:e.target.value})} className="input-admin w-full" placeholder="ID si connu"/></label><label className="label-admin">Motif<select value={reportForm.reason} onChange={e=>setReportForm({...reportForm,reason:e.target.value})} className="input-admin w-full">{reasons.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="label-admin">Détails<textarea rows={6} maxLength={6000} value={reportForm.details} onChange={e=>setReportForm({...reportForm,details:e.target.value})} className="input-admin w-full" placeholder="Décrivez précisément ce qui doit être vérifié."/></label><button disabled={busy} className="btn-primary w-full">{busy?<Loader2 size={15} className="animate-spin"/>:<ShieldAlert size={15}/>}Transmettre à la modération</button></div></form></div>}
  </div>
}

export default function SupportPage(){return <Suspense fallback={<div className="container-app py-10 text-sm text-gray-500">Chargement du support…</div>}><SupportPageContent/></Suspense>}
