"use client";

import { useEffect, useState } from "react";
import { ArrowDownToLine, Save, WalletCards, Banknote, ShoppingBag, BadgeDollarSign, Download } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import CurrencyPrice from "@/components/ui/CurrencyPrice";
import { useAuthGuard } from "@/hooks/useAuthGuard";
import GuardScreen from "@/components/ui/GuardScreen";
import InternationalPhoneField from "@/components/ui/InternationalPhoneField";

interface FinanceSummary { gross_revenue: string; total_earnings: string; premium_earnings: string; available_balance: string; paid_out: string; sales_count: number; commission_percent: number; premium_creator_pool_percent: number; minimum_payout: string; payout_profile_configured: boolean; recent_sales: { id: number; title: string; type: string; gross: string; earning: string; paid_at: string }[]; recent_premium_allocations: { id: number; amount: string; usage_weight: string; period_ends_at: string; created_at: string }[]; }
interface PayoutProfile { method: "bank" | "mobile_money" | "paypal"; account_name: string; account_reference: string; }
interface Payout { id: number; amount: string; status: string; requested_at: string; processed_at?: string | null; method: string; reference?: string; note?: string; }

export default function InstructorFinancePage() {
  const { ready, user } = useAuthGuard({ roles: ["instructor", "admin"], redirectTo: "/dashboard/instructor" });
  const [finance, setFinance] = useState<FinanceSummary | null>(null); const [profile, setProfile] = useState<PayoutProfile>({ method: "bank", account_name: "", account_reference: "" }); const [payouts, setPayouts] = useState<Payout[]>([]); const [amount, setAmount] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { const [f,p,po] = await Promise.all([api.get<FinanceSummary>("/payments/instructor/finance/"), api.get<PayoutProfile>("/payments/instructor/payout-profile/"), api.get<{results:Payout[]}|Payout[]>("/payments/payouts/")]); setFinance(f); setProfile(p); setPayouts(Array.isArray(po) ? po : po.results); setLoading(false); }
  useEffect(() => { if (ready) load().catch(() => setLoading(false)); }, [ready]);
  async function saveProfile() { setMessage(""); try { setProfile(await api.patch<PayoutProfile>("/payments/instructor/payout-profile/", profile)); setMessage("Destination de versement enregistrée."); } catch(e) { setMessage(e instanceof ApiError ? e.message : "Échec de l'enregistrement."); } }
  async function requestPayout() { setMessage(""); try { await api.post("/payments/payouts/", { amount: Number(amount) }); setAmount(""); await load(); setMessage("Demande de versement envoyée."); } catch(e) { setMessage(e instanceof ApiError ? e.message : "Impossible de demander le versement."); } }
  function exportSales() { const rows = [["Titre","Type","Brut","Votre part","Date"], ...(finance?.recent_sales || []).map(s => [s.title,s.type,s.gross,s.earning,s.paid_at || ""])]; const blob = new Blob([rows.map(r => r.map(v => `"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n")], {type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download="kalanpro-ventes.csv"; a.click(); URL.revokeObjectURL(url); }
  if (!ready) return <GuardScreen />;
  return <div className="min-w-0"><div className="mb-6"><h1 className="text-xl font-bold">Revenus & versements</h1><p className="mt-1 text-sm text-gray-500">Suivez vos ventes, configurez votre destination et demandez vos versements.</p></div>{loading ? <div className="card p-8 text-center text-gray-500">Chargement...</div> : <>
    <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<ShoppingBag size={18}/>} label="Ventes" value={finance?.sales_count || 0}/><Stat icon={<BadgeDollarSign size={18}/>} label="CA généré" value={<CurrencyPrice value={finance?.gross_revenue || 0} />}/><Stat icon={<WalletCards size={18}/>} label="Disponible" value={<CurrencyPrice value={finance?.available_balance || 0} />}/><Stat icon={<Banknote size={18}/>} label="Déjà versé" value={<CurrencyPrice value={finance?.paid_out || 0} />}/></div>
    {(Number(finance?.premium_earnings || 0) !== 0 || (finance?.recent_premium_allocations?.length || 0) > 0) && <div className="mb-6 rounded-2xl border border-violet-100 bg-violet-50/50 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-extrabold text-violet-900">Revenus KalanPro Premium</p><p className="mt-1 text-xs leading-5 text-violet-700">Votre part provient du pool créateurs ({finance?.premium_creator_pool_percent ?? 0}% des périodes éligibles), réparti selon les contenus Premium distincts réellement utilisés.</p></div><div className="shrink-0 text-left sm:text-right"><p className="text-lg font-extrabold text-violet-900"><CurrencyPrice value={finance?.premium_earnings || 0} /></p><p className="text-[10px] uppercase tracking-wide text-violet-600">net Premium comptabilisé</p></div></div>{(finance?.recent_premium_allocations?.length || 0) > 0 && <div className="mt-3 flex flex-wrap gap-2">{finance!.recent_premium_allocations.slice(0,4).map((a) => <span key={a.id} className="rounded-full bg-white px-2.5 py-1 text-[11px] font-semibold text-violet-700"><CurrencyPrice value={a.amount} /> · période fin {new Date(a.period_ends_at).toLocaleDateString("fr-FR")}</span>)}</div>}</div>}
    <div className="mb-6 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="card p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="font-bold">Ventes récentes</h2><p className="text-xs text-gray-500">Commission plateforme : {finance?.commission_percent ?? 0}%</p></div><button onClick={exportSales} className="btn-outline !py-1.5 !text-xs"><Download size={13}/> CSV</button></div><div className="max-h-[360px] overflow-auto"><table className="w-full min-w-[520px] text-sm"><thead className="sticky top-0 bg-gray-50 text-left text-xs text-gray-500"><tr><th className="px-3 py-2">Contenu</th><th className="px-3 py-2">Brut</th><th className="px-3 py-2">Votre part</th><th className="px-3 py-2">Date</th></tr></thead><tbody className="divide-y divide-gray-100">{(finance?.recent_sales || []).map(s => <tr key={s.id}><td className="px-3 py-2"><p className="font-medium">{s.title}</p><p className="text-[10px] uppercase text-gray-400">{s.type}</p></td><td className="px-3 py-2"><CurrencyPrice value={s.gross} /></td><td className="px-3 py-2 font-semibold text-brand-700"><CurrencyPrice value={s.earning} /></td><td className="px-3 py-2 text-xs text-gray-500">{s.paid_at ? new Date(s.paid_at).toLocaleDateString("fr-FR") : "-"}</td></tr>)}{!finance?.recent_sales?.length && <tr><td colSpan={4} className="px-3 py-8 text-center text-gray-400">Aucune vente payée.</td></tr>}</tbody></table></div></div>
    <div className="card p-5"><h2 className="font-bold">Recevoir mon argent</h2><p className="mb-4 text-xs text-gray-500">Retrait minimum : <CurrencyPrice value={finance?.minimum_payout || 0} /> (équivalent affiché).</p><div className="space-y-3"><select value={profile.method} onChange={e=>setProfile({...profile,method:e.target.value as PayoutProfile["method"],account_reference:""})} className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"><option value="bank">Virement bancaire</option><option value="mobile_money">Mobile Money</option><option value="paypal">PayPal</option></select><input value={profile.account_name} onChange={e=>setProfile({...profile,account_name:e.target.value})} placeholder="Nom du titulaire" className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"/>{profile.method==="mobile_money"?<InternationalPhoneField value={profile.account_reference} onChange={(account_reference)=>setProfile({...profile,account_reference})} preferredCountry={user?.country} label="Numéro Mobile Money" helperText="Choisissez l’indicatif du pays puis saisissez le numéro rattaché au wallet Mobile Money."/>:<input type={profile.method==="paypal"?"email":"text"} value={profile.account_reference} onChange={e=>setProfile({...profile,account_reference:e.target.value})} placeholder={profile.method==="bank"?"IBAN / RIB":"Email PayPal"} className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"/>}<button onClick={saveProfile} className="btn-outline w-full !py-2 !text-xs"><Save size={14}/> Enregistrer la destination</button><div className="border-t border-gray-100 pt-3"><label className="mb-1 block text-xs font-medium text-gray-500">Montant du retrait (EUR)</label><p className="mb-2 text-[10px] leading-4 text-gray-400">La devise de la navbar ne change que l'affichage. Les versements sont comptabilisés et demandés en EUR.</p><div className="flex gap-2"><input type="number" min={0} value={amount} onChange={e=>setAmount(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-gray-200 px-3 py-2 text-sm"/><button onClick={requestPayout} className="btn-primary !px-3 !py-2 !text-xs"><ArrowDownToLine size={14}/> Demander</button></div></div>{message && <p className="text-xs text-gray-600">{message}</p>}</div></div></div>
    <div className="card overflow-hidden"><div className="border-b border-gray-100 p-5"><h2 className="font-bold">Historique des versements</h2><p className="text-xs text-gray-500">Statut et référence de chaque demande.</p></div><div className="max-h-[360px] overflow-auto"><table className="w-full min-w-[620px] text-sm"><thead className="sticky top-0 bg-gray-50 text-left text-xs text-gray-500"><tr><th className="px-4 py-3">Demandé le</th><th className="px-4 py-3">Méthode</th><th className="px-4 py-3">Montant</th><th className="px-4 py-3">Statut</th><th className="px-4 py-3">Référence</th></tr></thead><tbody className="divide-y divide-gray-100">{payouts.map(p => <tr key={p.id}><td className="px-4 py-3 text-xs text-gray-500">{new Date(p.requested_at).toLocaleDateString("fr-FR")}</td><td className="px-4 py-3">{p.method}</td><td className="px-4 py-3 font-semibold"><CurrencyPrice value={p.amount} /></td><td className="px-4 py-3"><span className={`badge ${p.status==="paid"?"bg-emerald-50 text-emerald-700":p.status==="failed"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{p.status}</span></td><td className="px-4 py-3 text-xs text-gray-500">{p.reference || "-"}</td></tr>)}{!payouts.length && <tr><td colSpan={5} className="px-4 py-8 text-center text-gray-400">Aucune demande.</td></tr>}</tbody></table></div></div>
  </>}</div>;
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:React.ReactNode}){return <div className="card flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-700">{icon}</span><div><p className="text-lg font-extrabold">{value}</p><p className="text-xs text-gray-500">{label}</p></div></div>}
