"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { Loader2, Users, XCircle, CheckCircle2 } from "lucide-react";
import EmployerNav from "@/components/opportunities/EmployerNav";
import EmployerOpportunityForm from "@/components/opportunities/EmployerOpportunityForm";
import { api, ApiError } from "@/lib/api";
import { useAuthGuard } from "@/hooks/useAuthGuard";
import GuardScreen from "@/components/ui/GuardScreen";
import type { Opportunity } from "@/types";
import { OPPORTUNITY_STATUS_LABELS, statusBadge } from "@/lib/opportunities";
export default function ManageOpportunityPage(){const {ready}=useAuthGuard();const {id}=useParams<{id:string}>();const [row,setRow]=useState<Opportunity|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);useEffect(()=>{if(ready)api.get<Opportunity>(`/opportunities/employer/opportunities/${id}/`).then(setRow).catch(e=>setError(e instanceof ApiError?e.message:"Offre introuvable."))},[ready,id]);async function action(name:"submit"|"close"|"filled"){if(!row)return;setBusy(true);try{const r=await api.post<Opportunity>(`/opportunities/employer/opportunities/${row.id}/${name}/`,{});setRow(r)}catch(e){setError(e instanceof ApiError?e.message:"Action impossible.")}finally{setBusy(false)}}if(!ready)return <GuardScreen/>;return <div className="container-app py-10"><EmployerNav/>{error&&<div className="mb-5 rounded-xl border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{!row?<div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-brand-600"/></div>:<><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-extrabold">{row.title}</h1><span className={`badge ${statusBadge(row.status)}`}>{OPPORTUNITY_STATUS_LABELS[row.status]}</span></div><p className="mt-1 text-xs text-gray-500">{row.applications_count||0} candidature{row.applications_count===1?"":"s"} · {row.views_count||0} vue{row.views_count===1?"":"s"}</p></div><div className="flex flex-wrap gap-2"><Link href={`/dashboard/employer/applications?opportunity=${row.id}`} className="btn-outline"><Users size={15}/> Candidatures</Link>{["draft","rejected"].includes(row.status)&&<button disabled={busy} onClick={()=>void action("submit")} className="btn-primary">Soumettre</button>}{row.status==="published"&&<button disabled={busy} onClick={()=>void action("close")} className="btn-outline !border-red-200 !text-red-700"><XCircle size={15}/> Clôturer</button>}{["published","closed"].includes(row.status)&&<button disabled={busy} onClick={()=>void action("filled")} className="btn-outline !border-emerald-200 !text-emerald-700"><CheckCircle2 size={15}/> Poste pourvu</button>}</div></div>{row.moderation_note&&<div className="mb-5 rounded-xl border border-red-100 bg-red-50 p-4 text-sm text-red-700"><b>Retour de modération :</b> {row.moderation_note}</div>}<EmployerOpportunityForm existing={row}/></>}</div>}
