import type { ReactNode } from "react";
import Link from "next/link";
import {
  Award, BriefcaseBusiness, CheckCircle2, ExternalLink, Github, Globe2, Linkedin, Mail,
  MapPin, PlayCircle, ShieldCheck, Target, Trophy, Wrench,
} from "lucide-react";
import { safeGet } from "@/lib/api";
import type { PublicPortfolio } from "@/types";

export const dynamic = "force-dynamic";

export default async function PublicPortfolioPage({params}:{params:Promise<{slug:string}>}) {
  const { slug } = await params;
  const result = await safeGet<PublicPortfolio|null>(`/projects/portfolio/${slug}/`, null);
  const p = result.data;
  if (!p) return <div className="container-app py-20"><div className="card mx-auto max-w-xl p-10 text-center"><h1 className="text-2xl font-bold">Portfolio indisponible</h1><p className="mt-2 text-sm text-gray-500">Ce portfolio n'existe pas ou n'est pas public.</p><Link href="/courses" className="btn-primary mt-6">Découvrir KalanPro</Link></div></div>;

  return <main className="min-h-screen bg-[#f7f8fa]">
    <section className="border-b border-gray-200 bg-white"><div className="container-app py-10 sm:py-14"><div className="flex flex-col gap-6 md:flex-row md:items-center"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-3xl bg-brand-50 text-3xl font-extrabold text-brand-700">{p.avatar?<img src={p.avatar} alt={p.full_name} loading="lazy" decoding="async" className="h-full w-full object-cover"/>:initials(p.full_name)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-extrabold tracking-tight">{p.full_name}</h1>{p.open_to_work&&<span className="badge bg-emerald-50 text-emerald-700"><BriefcaseBusiness size={12}/> Disponible</span>}</div><p className="mt-2 text-lg font-medium text-gray-600">{p.title||p.user_headline||"Portfolio KalanPro"}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-gray-400">{p.country&&<span className="flex items-center gap-1"><MapPin size={14}/>{p.country}</span>}{p.contact_email&&<a href={`mailto:${p.contact_email}`} className="flex items-center gap-1 hover:text-brand-700"><Mail size={14}/>{p.contact_email}</a>}</div><div className="mt-4 flex flex-wrap gap-2">{p.website_url&&<a href={p.website_url} target="_blank" rel="noreferrer" className="btn-outline !py-2 !text-xs"><Globe2 size={14}/> Site</a>}{p.linkedin_url&&<a href={p.linkedin_url} target="_blank" rel="noreferrer" className="btn-outline !py-2 !text-xs"><Linkedin size={14}/> LinkedIn</a>}{p.github_url&&<a href={p.github_url} target="_blank" rel="noreferrer" className="btn-outline !py-2 !text-xs"><Github size={14}/> GitHub</a>}</div></div></div>{p.about&&<p className="mt-8 max-w-4xl whitespace-pre-wrap text-sm leading-7 text-gray-600">{p.about}</p>}{p.skills?.length>0&&<div className="mt-6 flex flex-wrap gap-2">{p.skills.map(s=><span key={s} className="rounded-full bg-gray-100 px-3 py-1.5 text-xs font-semibold text-gray-600">{s}</span>)}</div>}</div></section>

    <section className="container-app py-10 sm:py-14"><div className="mb-6"><h2 className="text-2xl font-bold">Projets & réalisations</h2><p className="mt-1 text-sm text-gray-500">Les éléments « Vérifié KalanPro » ont été évalués et validés par un instructeur.</p></div>{p.items.length===0?<div className="card p-10 text-center text-gray-500">Aucun projet public pour le moment.</div>:<div className="grid gap-5 lg:grid-cols-2">{p.items.map(item=><article key={item.id} className={`card overflow-hidden ${item.featured?"ring-2 ring-brand-100":""}`}><div className="aspect-[16/10] overflow-hidden bg-gray-100">{item.cover_image?<img src={item.cover_image} alt={item.title} loading="lazy" decoding="async" className="h-full w-full object-cover object-center"/>:<div className="grid h-full place-items-center text-gray-300"><Globe2 size={34}/></div>}</div><div className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-bold">{item.title}</h3>{item.role&&<p className="mt-1 text-xs font-semibold text-brand-700">Rôle : {item.role}</p>}</div>{item.is_verified&&<span className="badge shrink-0 bg-emerald-50 text-emerald-700"><ShieldCheck size={12}/> Vérifié KalanPro</span>}</div>{(item.started_at||item.completed_at)&&<p className="mt-2 text-[11px] text-gray-400">{formatPeriod(item.started_at,item.completed_at)}</p>}{item.is_verified&&<div className="mt-3 rounded-xl bg-emerald-50/70 p-3 text-[11px] leading-5 text-emerald-900"><p className="font-semibold">{item.verified_assignment_title}</p><p>{item.verified_course_title} · corrigé par {item.verified_instructor_name}</p>{item.score&&<p className="mt-1 font-bold"><CheckCircle2 size={12} className="mr-1 inline"/>Score {item.score.value}/{item.score.max||"—"}</p>}</div>}
      {item.description&&<p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-gray-600">{item.description}</p>}
      <div className="mt-4 grid gap-3 sm:grid-cols-2">{item.problem&&<Evidence icon={<Target size={14}/>} label="Problème / contexte" text={item.problem}/>} {item.objective&&<Evidence icon={<Target size={14}/>} label="Objectif" text={item.objective}/>} {item.outcome&&<Evidence icon={<Trophy size={14}/>} label="Résultat / impact" text={item.outcome}/>}</div>
      {(item.stack.length>0||item.skills.length>0)&&<div className="mt-4"><p className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wide text-gray-400"><Wrench size={12}/> Stack & compétences</p><div className="mt-2 flex flex-wrap gap-1.5">{Array.from(new Set([...item.stack,...item.skills])).map(s=><span key={s} className="rounded-full bg-gray-100 px-2 py-1 text-[10px] font-medium text-gray-600">{s}</span>)}</div></div>}
      <div className="mt-5 flex flex-wrap gap-2">{item.external_url&&<a href={item.external_url} target="_blank" rel="noreferrer" className="btn-primary !py-2 !text-xs"><ExternalLink size={13}/> Voir le projet</a>}{item.video_url&&<a href={item.video_url} target="_blank" rel="noreferrer" className="btn-outline !py-2 !text-xs"><PlayCircle size={13}/> Démo vidéo</a>}{item.repository_url&&<a href={item.repository_url} target="_blank" rel="noreferrer" className="btn-outline !py-2 !text-xs"><Github size={13}/> Code/source</a>}</div></div></article>)}</div>}</section>

    {p.certificates.length>0&&<section className="border-y border-gray-200 bg-white"><div className="container-app py-10 sm:py-14"><div className="mb-6"><h2 className="flex items-center gap-2 text-2xl font-bold"><Award className="text-amber-500"/> Certificats vérifiables</h2><p className="mt-1 text-sm text-gray-500">Sélectionnés par le titulaire et actuellement valides dans le registre KalanPro.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{p.certificates.map(cert=><article key={cert.id} className={`rounded-2xl border p-5 ${cert.featured?"border-amber-200 bg-amber-50/40":"border-gray-100"}`}><div className="flex items-start justify-between gap-3"><Award className="text-amber-500"/><span className="badge bg-emerald-50 text-emerald-700"><ShieldCheck size={12}/> Valide</span></div><h3 className="mt-4 font-bold">{cert.content_title}</h3><p className="mt-1 text-xs text-gray-500">{cert.issuer_name}{cert.instructor_name?` · ${cert.instructor_name}`:""}</p><p className="mt-3 text-[11px] text-gray-400">N° {cert.certificate_number} · {new Date(cert.issued_at).toLocaleDateString("fr-FR")}</p>{cert.skills.length>0&&<div className="mt-3 flex flex-wrap gap-1">{cert.skills.slice(0,5).map(skill=><span key={skill} className="rounded-full bg-white px-2 py-1 text-[10px] text-gray-600">{skill}</span>)}</div>}<a href={cert.verification_url} target="_blank" rel="noreferrer" className="btn-outline mt-4 !py-2 !text-xs"><ShieldCheck size={13}/> Vérifier</a></article>)}</div></div></section>}

    <footer className="border-t border-gray-200 bg-white"><div className="container-app flex flex-wrap items-center justify-between gap-3 py-6 text-xs text-gray-400"><span>Portfolio professionnel propulsé par KalanPro</span><Link href="/courses" className="font-semibold text-brand-700">Développer mes compétences</Link></div></footer>
  </main>;
}

function Evidence({icon,label,text}:{icon:ReactNode;label:string;text:string}){return <div className="rounded-xl border border-gray-100 bg-gray-50 p-3"><p className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wide text-gray-400">{icon}{label}</p><p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-gray-600">{text}</p></div>}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"KP"}
function formatPeriod(start:string|null,end:string|null){const f=(v:string)=>new Date(`${v}T00:00:00`).toLocaleDateString("fr-FR",{month:"short",year:"numeric"});return start&&end?`${f(start)} – ${f(end)}`:start?`Depuis ${f(start)}`:end?`Terminé ${f(end)}`:""}
