# Generated by Django 5.0.7 on 2026-08-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.interactiveformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Carte bancaire (Stripe)'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money (Orange Money, MTN, Wave, M-Pesa...)')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('course', 'Cours'), ('pdf', 'PDF'), ('formation', 'Formation interactive')], max_length=10),
        ),
    ]
