# Generated manually for LearnEas v48
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=140)),
                ("company_size", models.CharField(blank=True, choices=[("solo", "Indépendant"), ("1-10", "1–10"), ("11-50", "11–50"), ("51-200", "51–200"), ("201-1000", "201–1000"), ("1000+", "1000+")], max_length=20)),
                ("website_url", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="employers/logos/%Y/%m/")),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("pending", "En attente"), ("approved", "Approuvé"), ("rejected", "Refusé"), ("suspended", "Suspendu")], db_index=True, default="pending", max_length=20)),
                ("review_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_employer_profiles", to=settings.AUTH_USER_MODEL)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="employer_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["company_name"]},
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("headline", models.CharField(blank=True, max_length=180)),
                ("summary", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("desired_roles", models.JSONField(blank=True, default=list)),
                ("preferred_kinds", models.JSONField(blank=True, default=list)),
                ("preferred_work_modes", models.JSONField(blank=True, default=list)),
                ("preferred_countries", models.JSONField(blank=True, default=list)),
                ("minimum_salary", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("salary_currency", models.CharField(default="EUR", max_length=3)),
                ("availability", models.CharField(choices=[("immediate", "Disponible immédiatement"), ("2_weeks", "Sous 2 semaines"), ("1_month", "Sous 1 mois"), ("open", "À l'écoute"), ("unavailable", "Indisponible")], default="open", max_length=20)),
                ("years_experience", models.PositiveSmallIntegerField(default=0)),
                ("resume", models.FileField(blank=True, null=True, upload_to="opportunities/resumes/%Y/%m/")),
                ("is_searchable", models.BooleanField(db_index=True, default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="candidate_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(blank=True, max_length=240, unique=True)),
                ("kind", models.CharField(choices=[("job", "Emploi"), ("internship", "Stage"), ("freelance", "Freelance"), ("mission", "Mission")], db_index=True, default="job", max_length=20)),
                ("contract_type", models.CharField(choices=[("full_time", "Temps plein"), ("part_time", "Temps partiel"), ("fixed_term", "CDD"), ("permanent", "CDI"), ("internship", "Stage"), ("freelance", "Freelance"), ("project", "Projet / mission")], default="full_time", max_length=20)),
                ("work_mode", models.CharField(choices=[("remote", "À distance"), ("hybrid", "Hybride"), ("onsite", "Sur site")], db_index=True, default="remote", max_length=20)),
                ("experience_level", models.CharField(choices=[("entry", "Débutant / premier emploi"), ("junior", "Junior"), ("mid", "Intermédiaire"), ("senior", "Senior"), ("lead", "Lead / management")], default="entry", max_length=20)),
                ("description", models.TextField()),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("skills_required", models.JSONField(blank=True, default=list)),
                ("skills_optional", models.JSONField(blank=True, default=list)),
                ("country", models.CharField(blank=True, db_index=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("remote_worldwide", models.BooleanField(default=False)),
                ("salary_min", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("salary_max", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("salary_currency", models.CharField(default="EUR", max_length=3)),
                ("salary_period", models.CharField(choices=[("hour", "Par heure"), ("day", "Par jour"), ("month", "Par mois"), ("year", "Par an"), ("project", "Forfait mission")], default="month", max_length=20)),
                ("show_salary", models.BooleanField(default=True)),
                ("apply_mode", models.CharField(choices=[("internal", "Candidature LearnEas"), ("external", "Lien externe")], default="internal", max_length=20)),
                ("external_application_url", models.URLField(blank=True)),
                ("application_deadline", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(choices=[("draft", "Brouillon"), ("published", "Publiée"), ("closed", "Clôturée"), ("archived", "Archivée")], db_index=True, default="draft", max_length=20)),
                ("featured", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="opportunities", to="opportunities.employerprofile")),
            ],
            options={"ordering": ["-featured", "-published_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="OpportunityApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("submitted", "Candidature envoyée"), ("reviewing", "En cours d'étude"), ("shortlisted", "Présélectionné"), ("interview", "Entretien"), ("offer", "Offre"), ("hired", "Retenu"), ("rejected", "Non retenu"), ("withdrawn", "Retirée")], db_index=True, default="submitted", max_length=20)),
                ("cover_letter", models.TextField(blank=True)),
                ("resume_file", models.FileField(blank=True, null=True, upload_to="opportunities/applications/%Y/%m/")),
                ("share_portfolio", models.BooleanField(default=True)),
                ("match_score", models.PositiveSmallIntegerField(default=0)),
                ("candidate_name_snapshot", models.CharField(max_length=220)),
                ("candidate_email_snapshot", models.EmailField(max_length=254)),
                ("country_snapshot", models.CharField(blank=True, max_length=100)),
                ("headline_snapshot", models.CharField(blank=True, max_length=180)),
                ("skills_snapshot", models.JSONField(blank=True, default=list)),
                ("portfolio_snapshot", models.JSONField(blank=True, default=dict)),
                ("certificates_snapshot", models.JSONField(blank=True, default=list)),
                ("verified_projects_snapshot", models.JSONField(blank=True, default=list)),
                ("recruiter_note", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="opportunity_applications", to=settings.AUTH_USER_MODEL)),
                ("opportunity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="applications", to="opportunities.opportunity")),
            ],
            options={"ordering": ["-applied_at"]},
        ),
        migrations.AddConstraint(
            model_name="opportunityapplication",
            constraint=models.UniqueConstraint(fields=("opportunity", "candidate"), name="uniq_opportunity_candidate_application"),
        ),
        migrations.AddIndex(model_name="employerprofile", index=models.Index(fields=["status", "created_at"], name="opp_emp_status_created_idx")),
        migrations.AddIndex(model_name="candidateprofile", index=models.Index(fields=["is_searchable", "-updated_at"], name="opp_candidate_search_idx")),
        migrations.AddIndex(model_name="opportunity", index=models.Index(fields=["status", "kind", "work_mode", "-published_at"], name="opp_listing_public_idx")),
        migrations.AddIndex(model_name="opportunity", index=models.Index(fields=["employer", "status", "-created_at"], name="opp_listing_employer_idx")),
        migrations.AddIndex(model_name="opportunityapplication", index=models.Index(fields=["opportunity", "status", "-applied_at"], name="opp_app_listing_status_idx")),
        migrations.AddIndex(model_name="opportunityapplication", index=models.Index(fields=["candidate", "status", "-applied_at"], name="opp_app_candidate_status_idx")),
    ]
