"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { Award, ExternalLink, Search, ShieldCheck } from "lucide-react";
import { api } from "@/lib/api";
import type { Certificate, Paginated } from "@/types";
import DashboardNav from "@/components/dashboard/DashboardNav";
import GuardScreen from "@/components/ui/GuardScreen";
import { useAuthGuard } from "@/hooks/useAuthGuard";

export default function MyCertificates(){
 const {ready}=useAuthGuard(); const [items,setItems]=useState<Certificate[]>([]); const [q,setQ]=useState(""); const [status,setStatus]=useState("all"); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!ready)return; api.get<Paginated<Certificate>|Certificate[]>("/enrollments/certificates/").then((d:any)=>setItems(d.results||d)).finally(()=>setLoading(false));},[ready]);
 const filtered=useMemo(()=>items.filter(c=>(status==="all"||c.effective_status===status)&&(`${c.content_title} ${c.certificate_number} ${c.instructor_name}`.toLowerCase().includes(q.toLowerCase()))),[items,q,status]);
 if(!ready)return <GuardScreen/>;
 return <div className="container-app py-10"><DashboardNav role="student"/><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Mes certificats</h1><p className="text-sm text-gray-500">Retrouvez, imprimez, partagez et vérifiez vos certificats LearnEas.</p></div><Link href="/certificates/verify" className="btn-outline"><ShieldCheck size={16}/> Vérifier un certificat</Link></div><div className="mb-5 flex flex-wrap gap-2"><label className="relative w-full flex-1 sm:min-w-[240px]"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input className="input-admin w-full pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Titre, instructeur, numéro..."/></label><select className="input-admin" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tous les statuts</option><option value="active">Valides</option><option value="expired">Expirés</option><option value="revoked">Révoqués</option></select></div>{loading?<p className="text-sm text-gray-400">Chargement...</p>:filtered.length===0?<div className="card p-10 text-center text-gray-500"><Award className="mx-auto mb-2 text-gray-300"/>Aucun certificat correspondant.</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(c=><article key={c.id} className="card p-5"><div className="flex items-start justify-between gap-3"><Award className="text-amber-500"/><span className={`badge ${c.effective_status==="active"?"bg-emerald-50 text-emerald-700":c.effective_status==="revoked"?"bg-red-50 text-red-600":"bg-gray-100 text-gray-600"}`}>{c.effective_status==="active"?"Valide":c.effective_status==="revoked"?"Révoqué":"Expiré"}</span></div><h2 className="mt-4 font-bold">{c.content_title}</h2><p className="mt-1 text-xs text-gray-500">{c.content_type==="course"?"Cours":"Formation live"} · {c.instructor_name}</p><p className="mt-3 text-xs text-gray-400">N° {c.certificate_number}</p><div className="mt-4 flex gap-2"><Link className="btn-primary flex-1 !py-2 !text-xs" href={`/certificates/${c.id}`}>Voir</Link><a className="btn-outline !px-3 !py-2" href={c.verification_url} target="_blank" rel="noreferrer" title="Vérification publique"><ExternalLink size={14}/></a></div></article>)}</div>}</div>;
}
