"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CalendarPlus, CheckCircle2, Eye, EyeOff, Loader2, PlusCircle, Trash2, Video } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import { MentorshipBooking, MentorshipOffering, Paginated } from "@/types";
import { useAuthGuard } from "@/hooks/useAuthGuard";
import GuardScreen from "@/components/ui/GuardScreen";
import CurrencyPrice from "@/components/ui/CurrencyPrice";

const emptyForm={title:"",description:"",duration_minutes:30,price:"0",language:"Français",timezone:"Africa/Abidjan",booking_notice_hours:2,cancellation_notice_hours:12,published:false};

export default function InstructorMentorshipPage(){
  const{ready}=useAuthGuard({roles:["instructor","admin"],redirectTo:"/dashboard/instructor"});
  const[offers,setOffers]=useState<MentorshipOffering[]>([]); const[bookings,setBookings]=useState<MentorshipBooking[]>([]); const[form,setForm]=useState(emptyForm); const[slotDraft,setSlotDraft]=useState<Record<number,string>>({}); const[busy,setBusy]=useState(false); const[error,setError]=useState(""); const[message,setMessage]=useState("");
  async function load(){const [o,b]=await Promise.all([api.get<MentorshipOffering[]>("/mentorship/offerings/mine/"),api.get<Paginated<MentorshipBooking>|MentorshipBooking[]>("/mentorship/bookings/?as_mentor=1&ordering=-created_at")]);setOffers(o);setBookings(Array.isArray(b)?b:b.results)}
  useEffect(()=>{if(ready)load().catch(e=>setError(e instanceof ApiError?e.message:"Chargement impossible."))},[ready]);
  async function createOffer(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api.post("/mentorship/offerings/",form);setForm(emptyForm);setMessage("Offre créée. Ajoutez maintenant vos créneaux.");await load()}catch(e){setError(e instanceof ApiError?e.message:"Création impossible.")}finally{setBusy(false)}}
  async function toggle(o:MentorshipOffering){try{await api.patch(`/mentorship/offerings/${o.slug}/`,{published:!o.published});await load()}catch(e){setError(e instanceof ApiError?e.message:"Modification impossible.")}}
  async function addSlot(o:MentorshipOffering){const raw=slotDraft[o.id];if(!raw){setError("Choisissez une date et une heure.");return}try{await api.post("/mentorship/slots/",{offering:o.id,starts_at:new Date(raw).toISOString(),is_active:true});setSlotDraft(x=>({...x,[o.id]:""}));await load()}catch(e){setError(e instanceof ApiError?e.message:"Créneau impossible.")}}
  async function removeSlot(id:number){if(!confirm("Supprimer définitivement ce créneau sans historique ?"))return;try{await api.del(`/mentorship/slots/${id}/`);await load()}catch(e){setError(e instanceof ApiError?e.message:"Suppression impossible.")}}
  async function toggleSlot(id:number,is_active:boolean){try{await api.patch(`/mentorship/slots/${id}/`,{is_active:!is_active});await load()}catch(e){setError(e instanceof ApiError?e.message:"Modification du créneau impossible.")}}
  async function complete(b:MentorshipBooking){const note=prompt("Note de suivi pour l'apprenant (facultatif) :")||"";try{await api.post(`/mentorship/bookings/${b.id}/complete/`,{mentor_note:note});await load()}catch(e){setError(e instanceof ApiError?e.message:"Clôture impossible.")}}
  const upcoming=useMemo(()=>bookings.filter(b=>["pending_payment","confirmed"].includes(b.status)),[bookings]);
  if(!ready)return <GuardScreen/>;
  return <div className="min-w-0"><div className="mb-6"><h1 className="text-xl font-bold">Mentorat 1:1</h1><p className="mt-1 text-sm text-gray-500">Vendez des rendez-vous individuels, publiez vos disponibilités et utilisez la salle vidéo LearnEas.</p></div>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}
    <form onSubmit={createOffer} className="card mb-6 p-5"><h2 className="mb-4 font-bold">Nouvelle offre de mentorat</h2><div className="grid gap-3 md:grid-cols-2"><Field label="Titre"><input required className="input-admin w-full" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Prix (EUR)"><input type="number" min={0} step="0.01" className="input-admin w-full" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></Field><Field label="Durée (minutes)"><input type="number" min={15} max={180} className="input-admin w-full" value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:Number(e.target.value)})}/></Field><Field label="Fuseau horaire"><input className="input-admin w-full" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></Field><Field label="Réservation minimum (heures)"><input type="number" min={0} max={168} className="input-admin w-full" value={form.booking_notice_hours} onChange={e=>setForm({...form,booking_notice_hours:Number(e.target.value)})}/></Field><Field label="Annulation minimum (heures)"><input type="number" min={0} max={168} className="input-admin w-full" value={form.cancellation_notice_hours} onChange={e=>setForm({...form,cancellation_notice_hours:Number(e.target.value)})}/></Field></div><Field label="Description"><textarea required rows={4} className="input-admin w-full" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><button disabled={busy} className="btn-primary mt-4">{busy?<Loader2 size={15} className="animate-spin"/>:<PlusCircle size={15}/>}Créer l'offre</button></form>
    <div className="space-y-4">{offers.map(o=><section key={o.id} className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{o.title}</h2><span className={`badge ${o.published?"bg-emerald-50 text-emerald-700":"bg-gray-100 text-gray-600"}`}>{o.published?"Publiée":"Brouillon"}</span></div><p className="mt-1 text-xs text-gray-500">{o.duration_minutes} min · <CurrencyPrice value={o.price}/> · {o.timezone}</p></div><div className="flex gap-2"><Link href={`/mentorship/${o.slug}`} target="_blank" className="btn-outline !py-1.5 !text-xs"><Eye size={13}/>Voir</Link><button onClick={()=>toggle(o)} className="btn-outline !py-1.5 !text-xs">{o.published?<EyeOff size={13}/>:<Eye size={13}/>} {o.published?"Dépublier":"Publier"}</button></div></div><div className="mt-4 border-t border-gray-100 pt-4"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><input type="datetime-local" value={slotDraft[o.id]||""} onChange={e=>setSlotDraft(x=>({...x,[o.id]:e.target.value}))} className="input-admin"/><button onClick={()=>addSlot(o)} type="button" className="btn-outline !py-2 !text-xs"><CalendarPlus size={14}/>Ajouter un créneau</button></div><div className="mt-3 space-y-2">{(o.next_slots||[]).map(s=><div key={s.id} className={`flex flex-wrap items-center gap-2 rounded-lg border px-2.5 py-2 text-xs ${s.is_available?"border-gray-200 text-gray-600":s.is_active?"border-amber-100 bg-amber-50 text-amber-700":"border-gray-200 bg-gray-50 text-gray-500"}`}><span className="min-w-0 flex-1">{new Date(s.starts_at).toLocaleString("fr-FR",{dateStyle:"short",timeStyle:"short"})} · {s.is_active?(s.is_available?"Disponible":"Réservé / verrouillé"):"Désactivé"}</span><button type="button" onClick={()=>toggleSlot(s.id,s.is_active)} className="font-semibold text-brand-700">{s.is_active?"Désactiver":"Réactiver"}</button>{s.is_available&&<button type="button" onClick={()=>removeSlot(s.id)} className="text-red-500" title="Supprimer"><Trash2 size={12}/></button>}</div>)}</div></div></section>)}</div>
    <section className="card mt-6 p-5"><h2 className="font-bold">Rendez-vous à suivre</h2><div className="mt-4 space-y-2">{upcoming.map(b=><div key={b.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-gray-50 p-3 text-sm"><div className="min-w-0 flex-1"><p className="font-semibold">{b.learner_name} · {b.offering.title}</p><p className="text-xs text-gray-500">{new Date(b.slot.starts_at).toLocaleString("fr-FR",{dateStyle:"long",timeStyle:"short"})} · {b.status==="confirmed"?"Confirmé":"Paiement en attente"}</p></div>{b.status==="confirmed"&&b.join_session_id&&<Link href={`/live/session/${b.join_session_id}`} className="btn-primary !py-1.5 !text-xs"><Video size={13}/>Salle</Link>}{b.status==="confirmed"&&<button onClick={()=>complete(b)} className="btn-outline !py-1.5 !text-xs"><CheckCircle2 size={13}/>Clôturer</button>}</div>)}{!upcoming.length&&<p className="text-sm text-gray-400">Aucun rendez-vous actif.</p>}</div></section>
  </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-medium text-gray-600">{label}<div className="mt-1">{children}</div></label>}
